#ifndef DEFAULTPLUGIN_GLOBAL_H
#define DEFAULTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEFAULTPLUGIN_LIBRARY)
#  define DEFAULTPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define DEFAULTPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // DEFAULTPLUGIN_GLOBAL_H
