
#ifndef CLASSENUMS_H
#define CLASSENUMS_H

/// Enum defining unique IDs for all RS classes.
enum RSClass {
  NONE, // special case of no class or undefined class.

  // please leave all below entries in alphabetical order for easy lookup

  ANIMABLEENTITY,
  ANIMABLEENTITYNODE,
  ANIMATEDBOUNDARY,
  ANIMATEDEVENTOBJECT,
  ANIMATEDFLOORDECORATION,
  ANIMATEDWALLDECORATION,
  ANIMATION,
  ANIMATOR,

  BOUNDARY,

  CACHABLENODE,
  CACHE,
  CHARACTER,
  CHARACTERANIMATOR,
  CHATMESSAGE,
  CLIENT,
  COLLISIONDATA,
  COMBATBAR,
  COMBATBARDATA,

  DEQUE,
  DEQUENODE,
  DIRECTXMODEL,
  DIRECTXTOOLKIT,

  ENGINE,
  ENTITY,
  ENTITYDATA,
  EVENTOBJECT,

  FLOORDECORATION,

  GRANDEXCHANGEOFFER,
  GRAPHIC,
  GRAPHICCACHELOADER,
  GRAPHICSTOOLKIT,

  HARDREFERENCE,
  HASHTABLE,
  HINTARROW,

  ITEMCACHELOADER,
  ITEMDEFINITION,
  ITEMNODE,
  ITEMPILE,

  JAVAMODEL,
  JAVATOOLKIT,

  LINKEDLIST,
  LINKEDLISTNODE,

  MATRIX4F,
  MODEL,

  NODE,
  NPC,
  NPCCACHELOADER,
  NPCCOMPOSITE,

  OBJECTCACHELOADER,
  OBJECTCOMPOSITE,
  OBJECTDEFINITION,
  OBJECTNODE,
  OPENGLMODEL,
  OPENGLTOOLKIT,

  PLAYER,
  PLAYERCOMPOSITE,
  PLAYERFACADE,
  PROJECTILE,
  PROJECTILENODE,

  QUEUE,

  REGION,
  REGIONBASE,
  REGIONGRID,
  RENDERABLEENTITY,

  SKILL,
  SKILLCOMPOSITE,
  SOFTREFERENCE,

  TILE,
  TILEHEIGHTS,

  VARPS,
  VECTOR3D,

  WALLDECORATION,
  WIDGET,
  WIDGETCOMPONENT
};

#endif // CLASSENUMS_H
